### ISSUE TITLE
Using sitk::ChangeLabel

### ISSUE THREAD

**Issue by flaviu22** [yliu7366/yliu_utilities#1]
Hello Liu.

Have you used sitk::ChangeLabel in your code ? If you did, can you help me a little bit ? I got all labels from a sitk::Image:

```
	sitk::Image imgTemp(imgOrg);
	sitk::Image cc = sitk::ConnectedComponent(imgTemp);
	sitk::LabelIntensityStatisticsImageFilter statistics;
	statistics.Execute(cc, imgTemp);
	std::vector<int64_t>::iterator it;
	std::vector<int64_t> labels = statistics.GetLabels();
	for (it = labels.begin(); it != labels.end(); ++it)
	{
		TRACE(_T("Label: {%lu} -> Mean: {%f} Size: {%f}\n"),
			*it, statistics.GetMean(*it), statistics.GetPhysicalSize(*it));
	}

```
Now, I need to do only the last part, sitk::ChangeLabel:

```
	std::map<double, double> mapChange;
	mapChange.insert(std::make_pair(1049.634946, 0));

	imgOrg = sitk::ChangeLabel(cc, mapChange);

```
My question is, how to setup mapChnage to let in the outcome sitk::Image only the wanted part ? I mean, what should I feed into mapChange from Label ? Mean ? Size: ? Of course, I have tried one by one, none of  them seem to work ... 

My intend is to remove a bone from sitk::Image ...

Regards,
Flaviu.

P.S. My email address is flaviu2@yahoo.com

**Comment by yliu7366** [comment]
Please check out this example using sitk::ChangeLabel: https://github.com/abcsFrederick/yliu_utilities/blob/master/SimpleITK_remove_labels_less_than.py

**Comment by flaviu22** [comment]
Thank you, I have applied to my case, is not a proper result, but it's a starting point.
